name: urop_env
channels:
  - conda-forge
  - defaults
  - bioconda
  - anaconda
dependencies:
  - python=3.10
  - mamba
  - uproot
  - hist
  - boost-histogram
  - awkward
  - matplotlib
  - xrootd=5.5.1 
  - numpy
  - scipy
  - pandas
  - py-xgboost
  - pip
  - jupyter
  - pip:
    - SciencePlots
    - sweights
    - pyyaml
    - termcolor2
    - mplhep